import { Inter } from 'next/font/google';
import style from './layout.module.scss';
import './globals.css';
import Table from '@/components/table/table';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.app}>
          <Table>
            {children}
          </Table>
        </div>
      </body>
    </html>
  );
};
